// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package evaluactor

import (
	"fmt"
	"io"

	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf

var lengthBufState = []byte{128}

func (t *State) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufState); err != nil {
		return err
	}

	return nil
}

func (t *State) UnmarshalCBOR(r io.Reader) error {
	*t = State{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 0 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	return nil
}

var lengthBufEvalParams = []byte{129}

func (t *EvalParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufEvalParams); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Script (string) (string)
	if len(t.Script) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Script was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.Script))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Script)); err != nil {
		return err
	}
	return nil
}

func (t *EvalParams) UnmarshalCBOR(r io.Reader) error {
	*t = EvalParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Script (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.Script = string(sval)
	}
	return nil
}

var lengthBufEvalReturn = []byte{129}

func (t *EvalReturn) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufEvalReturn); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Result (string) (string)
	if len(t.Result) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Result was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.Result))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Result)); err != nil {
		return err
	}
	return nil
}

func (t *EvalReturn) UnmarshalCBOR(r io.Reader) error {
	*t = EvalReturn{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Result (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.Result = string(sval)
	}
	return nil
}
